name: WakaTime
on:
  push:
    branches:
      - main
jobs:
  wakatime_stats:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Generate WakaTime stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
